### PR TITLE
PROJECT refactor master server to accept chunk server hearbeats

### PR DESCRIPTION
**Pull request by nsalazar0429**
Screenshot 2024-12-15 at 2 21 31 AM

Screenshot 2024-12-15 at 2 21 50 AM

Screenshot 2024-12-15 at 2 22 17 AM

### CODE REVIEW

**Review by karandesai-sjsu — APPROVED** [review]
Seems good , the heartbeat code is to be added right i don't see it here!

**Comment by nsalazar0429** [comment]
> Seems good , the heartbeat code is to be added right i don't see it here! Could use code from client server implementation branch , if there are no additional requirements from the heartbeat other than liveliness check

There's actually. Look at `/chunkStatus`

**Comment by nsalazar0429** [comment]
Comment by @triptighanghas 

- [ ] heartbeat should accept list of chunks rather than map

**Comment by nsalazar0429** [comment]
Comments by @karandesai-sjsu 

- [ ] Add order int to chunk metadata

**Review by Phuoc-L — APPROVED** [review]
Everything looks good

**Review by karandesai-sjsu — APPROVED** [review]
good to go

**Pull request merged**
